/* 직원 테이블(S_EMP)과 급여 테이블(SALGRADE)을 JOIN하여
사원의 이름(S_EMP.NAME)과 급여(SALGRADE.SALARY), 그리고 해당 급여등급(SALGRADE.GRADE)을 나타내시오. */

SELECT E.NAME, E.SALARY, G.GRADE 급여등급
FROM S_EMP E, SALGRADE G
WHERE E.SALARY BETWEEN G.LOSAL AND G.HISAL;