/* S_EMP 테이블의 이름 컬럼에 인덱스를 추가하시오 */

SELECT * FROM IND;

SELECT * FROM S_EMP;

CREATE INDEX S_EMP_NAME
ON S_EMP(NAME);

SELECT * FROM IND
WHERE INDEX_NAME = 'S_EMP_NAME';

SELECT * FROM S_EMP
WHERE NAME = '홍길동';